Fix a call to retry_command function
This patch fixes a call to the function retry_command.
By some reasons we forgot to add a named argument 'command'
and in some cases function fails with error:
TypeError: argument of type 'NoneType' is not iterable
Reworked with change in ssh.py at exec_command func.

Change-Id: I659f643ea04034a8487bd7891510453501673223
Closes-Bug:1538045