Fix a call to retry_command function
This patch fixes a call to the function retry_command.
By some reasons we forgot to add a named argument 'command'
and in some cases function fails with error:
TypeError: argument of type 'NoneType' is not iterable

Change-Id: I4c0dd7f480bb1536af0d657b2221a43e2ae03c95
Closes-Bug:1538045
(cherry picked from commit befc27e62da5ca9e3ca4da85ab3e8f86cb0eb89a)